# .pre-commit-config.yaml
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: local
      hooks:
          - id: autoflake
            name: Remove unused variables and imports
            entry: poetry run autoflake
            args:
                [
                    "--in-place",
                    "--remove-all-unused-imports",
                    "--remove-unused-variables",
                    "--expand-star-imports",
                    "--ignore-init-module-imports",
                ]
            language: system
            types: [python]
            verbose: true
          - id: isort
            name: Sorting import statements
            entry: poetry run isort
            language: system
            types: [python]
            args: ["--filter-files"]
          - id: black
            name: Fix formatting for the entire codebase
            entry: poetry run black
            language: system
            types: [python]
            verbose: true
          - id: flake8
            name: Lint code base
            entry: poetry run flake8
            language: system
            types: [python]
            verbose: true
