version: 2

models:
    - name: dim_listings_cleansed
      description: Cleansed table containg AirBnB listing.
      columns:
          - name: listing_id
            description: Primary key for the listing
            tests:
                - unique
                - not_null
          - name: host_id
            description: The host's id. References the hosts table.
            tests:
                - not_null
                - relationships:
                      to: ref('dim_hosts_cleansed')
                      field: host_id
          - name: room_type
            description: The type of room for the current listing. Should be one of the following 'Entire home/apt', 'Private room', 'Shared room', or 'Hotel room'.
            tests:
                - accepted_values:
                      values:
                          [
                              "Entire home/apt",
                              "Private room",
                              "Shared room",
                              "Hotel room",
                          ]
          - name: minimum_nights
            description: '{{ doc("dim_listings_cleansed__min_nights") }}'
            tests:
                - positive_value

    - name: dim_hosts_cleansed
      description: Cleansed table for the AirBnB hosts
      columns:
          - name: host_id
            description: '{{ doc("dim_listings_cleansed__host_id") }}'
            tests:
                - not_null
                - unique

          - name: host_name
            description: The name of the host
            tests:
                - not_null

          - name: is_superhost
            description: Defines whether the hosts is a superhost.
            tests:
                - accepted_values:
                      values: ["t", "f"]

    - name: fct_reviews
      columns:
          - name: listing_id
            tests:
                - relationships:
                      to: ref('dim_listings_cleansed')
                      field: listing_id

          - name: reviewer_name
            tests:
                - not_null

          - name: review_sentiment
            tests:
                - accepted_values:
                      values: ["positive", "neutral", "negative"]
